#!/bin/sh
### BEGIN INIT INFO
# Provides:          coe-mi.pl
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       CAN over Ethernet Monitoring Interface
### END INIT INFO

SCRIPT=/usr/local/bin/coe-mi.pl
RUNAS=root

PIDFILE=/var/run/coe-mi.pid 	# fest in coe-mi.pl 
LOGFILE=/var/log/coe/coe-mi.log 	# fest in coe-mi.pl und /etc/logrotate.d/coe

start() {
  if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE"); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service ...' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service ...' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

status() {
    if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE"); then
    echo 'Service already running' >&2
    return 1
  else
    echo 'Service not running' >&2
    return 1
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
	status
	;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac